In [2]:
import numpy as np

In [4]:
#1. Create a null vector of size 10 but the fifth value which is 1.
a1 = np.zeros(10)
a1[4] = 1
print(a1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
#reate a vector with values ranging from 10 to 49.
a2 = np.arange(10,50)
print(a2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
 #Create a 3x3 matrix with values ranging from 0 to 8
a3 = np.arange(0,9).reshape((3,3))
print(a3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
nonzero = np.nonzero(np.array([1,2,0,0,4,0]))
print(nonzero[0].tolist())

[0, 1, 4]


In [17]:
#Create a 10x10 array with random values and find the minimum and maximum values.
arandom = np.random.rand(10,10)
print("Max is ",np.max(arandom))
print("Min is ",np.min(arandom))

Max is  0.9847901032269357
Min is  0.001154126935851152


In [20]:
# Create a random vector of size 30 and find the mean value.
arandom2 = np.random.random(30)
print(arandom2)
print("Mean is ",np.mean(arandom2))

[0.32002197 0.73658004 0.50344086 0.44558731 0.07772601 0.44836009
 0.00413609 0.20583436 0.21122026 0.30289977 0.85513901 0.6080271
 0.70120413 0.72246953 0.44395339 0.77649729 0.173997   0.9991842
 0.39002138 0.04049507 0.81893817 0.89948209 0.90822009 0.07431139
 0.91628777 0.2519528  0.83059131 0.35419881 0.18155283 0.04124278]
Mean is  0.4747857635448683
